/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNI */

#ifndef _Included_jni_JNI
#define _Included_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNI
 * Method:    getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_JNI_getNumber
  (JNIEnv *, jobject);

/*
 * Class:     jni_JNI
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNI_printHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
